server:
  port: 9909
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TeamDB
    username: Team
    password: improvement

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
#    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      encoding: UTF-8
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ibrohimovzuhriddin310@gmail.com
#    password: gxzblhgjnaydmysn


#  properties:
#    mail:
#      smtp:
#        #          ssl:
#        #            trust: "*"
#        auth: true
#        starttls:
#          enable: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
#        required: true